server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer
  webflux:
    base-path: /customers

controller:
  personal-customer:
    base-path: /personal
  business-customer:
    base-path: /business
  method:
    getAll:
    getById: /{id}
    register:
    updateById: /{id}
    deleteById: /{id}
  path-variable:
    id: id